default:
  type: postgres
  host: localhost
  port: 5432
  username: sysadmin
  password: sysadmin
  database: int_carreiras
  entities:
    - src/entity/*.ts
  migrations:
    - src/migration/*.ts

test:
  type: postgres
  host: localhost
  port: 5432
  username: sysadmin
  password: sysadmin
  database: test
  entities:
    - src/entity/*.ts
  migrations:
    - src/migration/*.ts
