default:
  type: postgres
  host: localhost
  port: 5432
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  database: ${DB}
  logging: false
  entities:
    - src/entity/*.ts
  migrations:
    - src/migration/*.ts
